version: '3.8'
services:
  nginx:
    image: nginx:1.27.5-alpine 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - app-network
    restart: always

volumes:
  certs:
networks:
  app-network:
